name: CI
on: [push]
jobs:
  unit-tests:
    runs-on: [self-hosted, ec2, squad]
    steps:
    - name: Pull repository
      uses: actions/checkout@v1
    - name: Run Composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Remove old Container
      run: docker stop squad-server || true  && docker rm squad-server || true
    - name: Run the Squad Server
      run: docker run -d --network=actions-runner_default --volume=$PWD/tests/ServerFolder:/home/steam/squad-dedicated -e PORT=7787 -e QUERYPORT=27165 -e RCONPORT=21114 --name=squad-server cm2network/squad
    - name: Wait for Squad Server to start up
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh
    - name: Wait for Squad Server to fully boot
      run: sleep 60
    - name: Log Squad Server
      run: docker logs squad-server
    - name: Run PHPUnit
      run: rm -f coverage.xml && vendor/bin/phpunit --coverage-clover=coverage.xml
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t $SquadRconPHPCodecovToken
    - name: Stop the Squad Server
      run: docker stop squad-server || true
